version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: crypto_ai_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: crypto_ai_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - crypto_ai_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto_ai_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/crypto_ai_db?authSource=admin
      - DB_NAME=crypto_ai_db
      - ETHERSCAN_API_KEY=E93F4XZ6EBEHDACUYUR4VNGH258YRGHQ91
      - TWITTER_API_KEY=h9FeLgu9uYhFZDysHkkRHlsWU
      - TWITTER_API_SECRET=tbNG9veNZVkUgDjcb7Z3cK8JMhDJJiKb6LaBIqrXiueMAlnl6J
      - TWITTER_BEARER_TOKEN=your_bearer_token_here
      - CLAUDE_API_KEY=your_claude_key_here
    depends_on:
      - mongodb
    networks:
      - crypto_ai_network
    volumes:
      - ./backend:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crypto_ai_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - crypto_ai_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  crypto_ai_network:
    driver: bridge
